### ISSUE TITLE
Not all emitted events are saved to local database.

### ISSUE THREAD

**Issue by JakeHartnell** [CommonGarden/CommonGarden-IoT#446]
Currently, we use nedb for a lightweight local database used for storing event data. Unfortunately, not all events are being stored... I hope to figure this out soon so will either have a fix or steps to reproduce.

**Comment by catbarph** [comment]
Could we, by default, first store things like sensor readings to the local device, and only send data to cloud on significant change? Perhaps this could help reduce cloud database size?

**Comment by ADD12** [comment]
I need this as well since many places we will want to use do not have a 
steady internet connection. Want to record offline and make AI 
adjustments locally in our Area Fog network. Cloud is ok to sync but 
steady connections are not possible. I have a mesh IIOT FOg network 
currently and puting 4 Intel Movidious Neural Compute sticks together 
for our other sensors. also want to add a Modem for remote connections 
to local fog network for access and control.

Alan DeRossett

**Comment by JakeHartnell** [comment]
I have a hunch moving the storage code (nedb or hypercore) to Thing.js will solve this. Things are a bit harder to keep track of in Grow.js, where we are dealing with an extension of an extension of an extension of the emit prototype. Arguably, this functionality belongs in Thing.js anyway. Will try to find time to do this soon.

**Comment by JakeHartnell** [comment]
Fixed in Thing.js v0.4.5

**Comment by JakeHartnell** [comment]
https://www.npmjs.com/package/Thing.js
